// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCroHUhOABMDyPilncWRGffFZi6fvMBkzI',
    appId: '1:722315641232:web:cf80936ddedefd9a527315',
    messagingSenderId: '722315641232',
    projectId: 'travel-mate-smd',
    authDomain: 'travel-mate-smd.firebaseapp.com',
    storageBucket: 'travel-mate-smd.firebasestorage.app',
    measurementId: 'G-VCWKK0FD23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCIeYtSlrLTS8SDI51SKd705W4par0kGE',
    appId: '1:722315641232:android:436e5d9c5d2f6a67527315',
    messagingSenderId: '722315641232',
    projectId: 'travel-mate-smd',
    storageBucket: 'travel-mate-smd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsV8rlR37SJ-hXIRPw1tjOhSryyysxDn0',
    appId: '1:722315641232:ios:8f3a419c77540b0e527315',
    messagingSenderId: '722315641232',
    projectId: 'travel-mate-smd',
    storageBucket: 'travel-mate-smd.firebasestorage.app',
    iosBundleId: 'com.example.smdProjectTravelmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsV8rlR37SJ-hXIRPw1tjOhSryyysxDn0',
    appId: '1:722315641232:ios:8f3a419c77540b0e527315',
    messagingSenderId: '722315641232',
    projectId: 'travel-mate-smd',
    storageBucket: 'travel-mate-smd.firebasestorage.app',
    iosBundleId: 'com.example.smdProjectTravelmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCroHUhOABMDyPilncWRGffFZi6fvMBkzI',
    appId: '1:722315641232:web:08018b77489bd5ff527315',
    messagingSenderId: '722315641232',
    projectId: 'travel-mate-smd',
    authDomain: 'travel-mate-smd.firebaseapp.com',
    storageBucket: 'travel-mate-smd.firebasestorage.app',
    measurementId: 'G-F58T7QRJG4',
  );
}
